name=input("Enter a name: ")
adjective1=input("Enter an adjective: ") 
adjective2=input("Enter an adjective: ")
adverb=input("Enter an adverb: ")
food=input("Enter a food: ")
food2=input("Enter another food: ")
noun=input("Enter a noun: ")
place=input("Enter a place: ")
Verb=input("Enter a verb: ")
print("Let's play Silly sentences!\n ")
print( name + " was planning a dream vacation to " + place)
print( name + " was especially looking forward to trying the local") 
print("cuisine, including " + adjective1+" "+food + " and " + food2+"\n\n") 
print( name + " will have to practice the language " + adverb ) 
print("to make it easier to " + Verb + " with people" ".\n\n")
print( name + " has a long list of sights to see, including the") 
print (noun + " museum and the " + adjective2 + " park.")